My First Plugin //Name
John Doe //Author
1.0.0 //Version
A Plugin, A Api, A Helper //Required Plugins
Verified //Verification
This is a cool plugin that does stuff! //Description
www.MyDownloadWebsite.com //Download
www.MyIconWebsite.com //Icon

My First Plugin //Name
John Doe //Author
1.0.0 //Version
A Plugin, A Api, A Helper
Verified
This is a cool plugin that does stuff!
www.MyDownloadWebsite.com
www.MyIconWebsite.com
END
